/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/shop.gltf -o src/components/experience/model/CoffeeShop.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeShop(props) {
  const { nodes, materials } = useGLTF('/shop.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bag001.geometry} material={materials.WhiteTwo} position={[0.489, 0.743, -0.925]} />
      <mesh geometry={nodes.Bag002.geometry} material={materials.WhiteTwo} position={[0.651, 0.58, -0.906]} rotation={[0, -0.306, 0]} />
      <mesh geometry={nodes.Bag003.geometry} material={materials.WhiteTwo} position={[0.533, 0.58, -0.906]} rotation={[0, -0.306, 0]} />
      <mesh geometry={nodes.Bag_small004.geometry} material={materials.WhiteTwo} position={[0.465, 0.418, -0.909]} rotation={[0, 0.743, 0]} />
      <mesh geometry={nodes.Bag_small.geometry} material={materials.WhiteTwo} position={[0.542, 0.418, -0.909]} rotation={[0, 0.743, 0]} />
      <mesh geometry={nodes.Bag.geometry} material={materials.WhiteTwo} position={[0.39, 0.255, -0.906]} rotation={[0, 0.504, 0]} />
      <mesh geometry={nodes.Bag_down.geometry} material={materials.WhiteTwo} position={[0.481, 0.286, -0.925]} rotation={[1.575, -0.056, -1.089]} />
      <mesh geometry={nodes.Bag_small001.geometry} material={materials.WhiteTwo} position={[-0.938, 0.645, -0.647]} rotation={[-Math.PI, 1.51, -Math.PI]} />
      <mesh geometry={nodes.Bag_small002.geometry} material={materials.WhiteTwo} position={[-0.938, 0.645, -0.719]} rotation={[-Math.PI, 1.51, -Math.PI]} />
      <mesh geometry={nodes.Bag_small003.geometry} material={materials.WhiteTwo} position={[-0.938, 0.645, -0.796]} rotation={[-Math.PI, 1.51, -Math.PI]} />
      <mesh geometry={nodes.Small_cup001.geometry} material={materials.WhiteTwo} position={[-0.453, 0.673, 0.758]} />
      <mesh geometry={nodes.Small_cup.geometry} material={materials.WhiteTwo} position={[-0.453, 0.673, 0.709]} />
      <mesh geometry={nodes.Small_cup002.geometry} material={materials.WhiteTwo} position={[-0.453, 0.673, 0.658]} />
      <mesh geometry={nodes.Small_cup004.geometry} material={materials.WhiteTwo} position={[-0.389, 0.673, 0.658]} />
      <mesh geometry={nodes.Small_cup005.geometry} material={materials.WhiteTwo} position={[-0.389, 0.673, 0.709]} />
      <mesh geometry={nodes.Small_cup003.geometry} material={materials.WhiteTwo} position={[-0.389, 0.673, 0.76]} />
      <mesh geometry={nodes.Big_cup001.geometry} material={materials.WhiteTwo} position={[0.511, 0.382, 0.434]} rotation={[-Math.PI, 0.527, 0]} />
      <mesh geometry={nodes.Big_cup002.geometry} material={materials.WhiteTwo} position={[0.511, 0.383, 0.198]} rotation={[0, -0.748, Math.PI]} />
      <mesh geometry={nodes.Big_cup003.geometry} material={materials.WhiteTwo} position={[-0.389, 0.468, 0.158]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.Big_cup004.geometry} material={materials.WhiteTwo} position={[-0.293, 0.468, 0.158]} rotation={[0, 1.42, -Math.PI]} />
      <mesh geometry={nodes.Big_cup.geometry} material={materials.WhiteTwo} position={[-0.487, 0.468, 0.081]} rotation={[-Math.PI, -1.302, 0]} />
      <mesh geometry={nodes.Bag004.geometry} material={materials.WhiteTwo} position={[0.517, 0.241, -0.914]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.French_press.geometry} material={materials.WhiteTwo} position={[0.558, 0.417, 0.324]} rotation={[0, -0.196, 0]} />
      <mesh geometry={nodes.Counter.geometry} material={materials.White} position={[0.059, 0.202, 0.438]} />
      <mesh geometry={nodes.Espresso_machine.geometry} material={materials.WhiteTwo} position={[-0.34, 0.491, 0.364]} />
      <mesh geometry={nodes.Grinder.geometry} material={materials.WhiteTwo} position={[-0.309, 0.626, 0.3]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Mocha_pot.geometry} material={materials.WhiteTwo} position={[-0.946, 0.984, -0.254]} rotation={[0, 1.062, 0]} />
      <mesh geometry={nodes.Mocha_pot001.geometry} material={materials.WhiteTwo} position={[-0.946, 0.984, -0.364]} rotation={[0, 1.062, 0]} />
      <mesh geometry={nodes.Small_mocha_pot.geometry} material={materials.WhiteTwo} position={[-0.946, 0.964, -0.481]} rotation={[0, 1.506, 0]} />
      <mesh geometry={nodes.Floor_plank.geometry} material={materials.WhiteTwo} position={[-0.928, 0.786, -0.41]} rotation={[-Math.PI, 1.486, -Math.PI]} />
      <mesh geometry={nodes.Floor_plank001.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank002.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank003.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank004.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank005.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank006.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Floor_plank007.geometry} material={materials.White} position={[-0.856, 0, 0.362]} />
      <mesh geometry={nodes.Chair001.geometry} material={materials.White} position={[0.515, 0.017, 0]} />
      <mesh geometry={nodes.Chair.geometry} material={materials.White} position={[0.413, 0.017, 0.601]} rotation={[-Math.PI, 0.976, -Math.PI]} />
      <mesh geometry={nodes.Shelf.geometry} material={materials.White} position={[-0.949, 0.629, -0.788]} />
      <mesh geometry={nodes.Shelf001.geometry} material={materials.White} position={[-0.948, 0.772, -0.552]} />
      <mesh geometry={nodes.Shelf002.geometry} material={materials.White} position={[-0.947, 0.91, -0.368]} />
      <mesh geometry={nodes.Small_bag.geometry} material={materials.WhiteTwo} position={[0.387, 0.418, -0.909]} rotation={[0, 0.743, 0]} />
      <mesh geometry={nodes.Table.geometry} material={materials.White} position={[0.54, 0.343, 0.317]} rotation={[0, 0, Math.PI]} />
      <mesh geometry={nodes.Big_Shelf.geometry} material={materials.White} position={[0.517, 0.241, -0.914]} rotation={[0, -Math.PI / 2, 0]} />
      <group position={[-0.736, 0.013, 0.837]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube208.geometry} material={materials.Skin} />
        <mesh geometry={nodes.Cube208_1.geometry} material={materials.Shoe} />
        <mesh geometry={nodes.Cube208_2.geometry} material={materials.Jeans} />
      </group>
      <mesh geometry={nodes.Wallsfloor.geometry} material={materials.White} />
      <mesh geometry={nodes.Subtext.geometry} material={materials.Text} position={[-0.993, 0.772, 0.803]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <meshStandardMaterial color="#fdbd48" />
      </mesh>
      <mesh geometry={nodes.Text.geometry} material={materials.Text} position={[-0.995, 0.898, 0.812]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <meshStandardMaterial color="#fdbd48" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/shop.gltf')
